<?php

namespace Database\Seeders;

use App\Models\PaisExportacion;
use Illuminate\Database\Seeder;

class PaisExportacionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $paises = [
            ['name' => 'Argentina', 'codigo_afip' => 200],
            ['name' => 'Bolivia', 'codigo_afip' => 202],
            ['name' => 'Brasil', 'codigo_afip' => 203],
            ['name' => 'Colombia', 'codigo_afip' => 205],
            ['name' => 'Costa Rica', 'codigo_afip' => 206],
            ['name' => 'Cuba', 'codigo_afip' => 207],
            ['name' => 'Chile', 'codigo_afip' => 208],
            ['name' => 'República Dominicana', 'codigo_afip' => 209],
            ['name' => 'Ecuador', 'codigo_afip' => 210],
            // Agregar más si tenés datos confirmados
        ];

// 101 BURKINA FASO    BURKINA FASO
// 102 ARGELIA ARGELIA
// 103 BOTSWANA    BOTSWANA
// 104 BURUNDI BURUNDI
// 105 CAMERUN CAMERUN
// 107 REP. CENTROAFRICANA.    REP.CENTROAFRICANA
// 108 CONGO   CONGO
// 109 REP.DEMOCRAT.DEL CONGO EX ZAIRE REP. DEMOCRAT. DEL CONGO EX ZAIRE
// 110 COSTA DE MARFIL COSTA DE MARFIL
// 111 CHAD    CHAD
// 112 BENIN   BENIN
// 113 EGIPTO  EGIPTO
// 115 GABON   GABON
// 116 GAMBIA  GAMBIA
// 117 GHANA   GHANA
// 118 GUINEA  GUINEA
// 119 GUINEA ECUATORIAL   GUINEA ECUATORIAL
// 120 KENYA   KENYA
// 121 LESOTHO LESOTHO
// 122 LIBERIA LIBERIA
// 123 LIBIA   LIBIA
// 124 MADAGASCAR  MADAGASCAR
// 125 MALAWI  MALAWI
// 126 MALI    MALI
// 127 MARRUECOS   MARRUECOS
// 128 MAURICIO,ISLAS  MAURICIO,ISLAS
// 129 MAURITANIA  MAURITANIA
// 130 NIGER   NIGER
// 131 NIGERIA NIGERIA
// 132 ZIMBABWE    ZIMBABWE
// 133 RWANDA  RWANDA
// 134 SENEGAL SENEGAL
// 135 SIERRA LEONA    SIERRA LEONA
// 136 SOMALIA SOMALIA
// 137 SWAZILANDIA SWAZILANDIA
// 138 SUDAN   SUDAN
// 139 TANZANIA    TANZANIA
// 140 TOGO    TOGO
// 141 TUNEZ   TUNEZ
// 142 UGANDA  UGANDA
// 143 REPUBLICA DE SUDAFRICA  REPUBLICA DE SUDAFRICA
// 144 ZAMBIA  ZAMBIA
// 145 TERRIT.VINCULADOS AL R UNIDO    AFRICA
// 146 TERRIT.VINCULADOS A ESPAÑA  AFRICA
// 147 TERRIT.VINCULADOS A FRANCIA AFRICA
// 148 TERRIT.VINCULADOS A PORTUGAL    AFRICA
// 149 ANGOLA  ANGOLA
// 150 CABO VERDE  ISLAS
// 151 MOZAMBIQUE  MOZAMBIQUE
// 152 SEYCHELLES  SEYCHELLES
// 153 DJIBOUTI    DJIBOUTI
// 155 COMORAS COMORAS
// 156 GUINEA BISSAU   GUINEA BISSAU
// 157 STO.TOME Y PRINCIPE STO.TOME Y PRINCIPE
// 158 NAMIBIA NAMIBIA
// 159 SUDAFRICA   SUDAFRICA
// 160 ERITREA ERITREA
// 161 ETIOPIA ETIOPIA
// 197 RESTO (AFRICA)  RESTO (AFRICA)
// 198 INDETERMINADO (AFRICA)  INDETERMINADO AFRICA)
// 200 ARGENTINA   ARGENTINA
// 201 BARBADOS    BARBADOS
// 202 BOLIVIA BOLIVIA
// 203 BRASIL  BRASIL
// 204 CANADA  CANADA
// 205 COLOMBIA    COLOMBIA
// 206 COSTA RICA  COSTA RICA
// 207 CUBA    CUBA
// 208 CHILE   CHILE
// 209 DOMINICANA,REP. DOMINICANA,REP.
// 210 ECUADOR ECUADOR
// 211 EL SALVADOR EL SALVADOR
// 212 ESTADOS UNIDOS  ESTADOS UNIDOS
// 213 GUATEMALA   GUATEMALA
// 214 GUYANA  GUYANA
// 215 HAITI   HAITI
// 216 HONDURAS    HONDURAS
// 217 JAMAICA JAMAICA
// 218 MEXICO  MEXICO
// 219 NICARAGUA   NICARAGUA
// 220 PANAMA  PANAMA
// 221 PARAGUAY    PARAGUAY
// 222 PERU    PERU
// 223 PUERTO RICO ESTADO ASOCIADO
// 224 TRINIDAD Y -TOBAGO  TRINIDAD Y TOBAGO
// 225 URUGUAY URUGUAY
// 226 VENEZUELA   VENEZUELA
// 227 TERRIT.VINCULADO AL R.UNIDO AMERICA
// 228 TER.VINCULADOS A DINAMARCA  AMERICA
// 229 TERRIT.VINCULADOS A FRANCIA AMERIC. AMERICA
// 230 TERRIT. HOLANDESES  TERRIT. HOLANDESES
// 231 TER.VINCULADOS A ESTADOS UNIDOS AMERICA
// 232 SURINAME    SURINAME
// 233 DOMINICA    DOMINICA
// 234 SANTA LUCIA SANTA LUCIA
// 235 SAN VICENTE Y LAS GRANADINS SAN VICENTE Y LAS GRANADINAS
// 236 BELICE  BELICE
// 237 ANTIGUA Y BARBUDA   ANTIGUA Y BARBUDA
// 238 S.CRISTOBAL Y NEVIS S.CRISTOBAL Y NEVIS
// 239 BAHAMAS BAHAMAS
// 240 GRANADA GRANADA
// 241 ANTILLAS HOLANDESAS TERRI.VINC.A PAISES BAJOS
// 242 ARUBA   
// 250 TIERRA DEL FUEGO    (AAE)
// 251 ZF LA PLATA BUENOS AIRES
// 252 ZF JUSTO DARACT SAN LUIS
// 253 ZF RIO GALLEGOS SANTA CRUZ
// 254 ISLAS MALVINAS  ISLAS MALVINAS
// 255 ZF TUCUMAN  TUCUMAN
// 256 ZF CORDOBA  CORDOBA
// 257 ZF MENDOZA  MENDOZA
// 258 ZF GENERAL PICO LA PAMPA
// 259 ZF COMODORO RIVADAVIA   CHUBUT
// 260 ZF IQUIQUE  CHILE
// 261 ZF PUNTA ARENAS CHILE
// 262 ZF SALTA    SALTA
// 263 ZF PASO DE LOS LIBRES   CORRIENTES
// 264 ZF PUERTO IGUAZU    MISIONES
// 265 SECTOR ANTARTICO ARG.   SECTOR ANTARTICO ARG.
// 270 ZF COLON    PANAMA
// 271 ZF WINNER (STA. C.DE LA SIERRA  BOLIVIA
// 280 ZF COLONIA  URUGUAY
// 281 ZF FLORIDA  URUGUAY
// 282 ZF LIBERTAD URUGUAY
// 283 ZF ZONAMERICA   EX MONTEVIDEO URUGUAY
// 284 ZF NUEVA HELVECIA   URUGUAY
// 285 ZF NUEVA PALMIRA    URUGUAY
// 286 ZF RIO NEGRO    URUGUAY
// 287 ZF RIVERA   URUGUAY
// 288 ZF SAN JOSE URUGUAY
// 291 ZF MANAOS   BRASIL
// 295 MAR ARG ZONA ECO.EX ARGENTINA
// 296 RIOS ARG NAVEG INTER    ARGENTINA
// 297 RESTO AMERICA   RESTO AMERICA
// 298 INDETERMINADO.(AMERICA) INDETERMINADO.(AMERICA)
// 301 AFGANISTAN  AFGANISTAN
// 302 ARABIA SAUDITA  ARABIA SAUDITA
// 303 BAHREIN BAHREIN
// 304 MYANMAR(EX-BIRMANIA)    MYANMAR(EX-BIRMANIA)
// 305 BUTAN   BUTAN
// 306 CAMBODYA(EX-KAMPUCHE    CAMBODYA(EX-KAMPUCHE
// 307 SRI LANKA   SRI LANKA
// 308 COREA DEMOCRATICA   COREA DEMOCRATICA
// 309 COREA REPUBLICANA   COREA REPUBLICANA
// 310 CHINA   CHINA
// 311 CHIPRE  CHIPRE
// 312 FILIPINAS   FILIPINAS
// 313 TAIWAN  TAIWAN
// 314 GAZA    GAZA
// 315 INDIA   INDIA
// 316 INDONESIA   INDONESIA
// 317 IRAK    IRAK
// 318 IRAN    IRAN
// 319 ISRAEL  ISRAEL
// 320 JAPON   JAPON
// 321 JORDANIA    JORDANIA
// 322 QATAR   QATAR
// 323 KUWAIT  KUWAIT
// 324 LAOS    LAOS
// 325 LIBANO  LIBANO
// 326 MALASIA MALASIA
// 327 MALDIVAS ISLAS  MALDIVAS ISLAS
// 328 OMAN    OMAN
// 329 MONGOLIA    MONGOLIA
// 330 NEPAL   NEPAL
// 331 EMIRATOS ARABES,UNID    EMIRATOS ARABES,UNID
// 332 PAKISTAN    PAKISTAN
// 333 SINGAPUR    SINGAPUR
// 334 SIRIA   SIRIA
// 335 THAILANDIA  THAILANDIA
// 336 TURQUIA TURQUIA
// 337 VIETNAM VIETNAM
// 341 HONG KONG   REG.ADM.ESP. DE CHINA
// 344 MACAO   MACAO(REG.ADM.ESPEC)
// 345 BANGLADESH  BANGLADESH
// 346 BRUNEI  BRUNEI
// 348 REPUBLICA DE YEMEN  REPUBLICA DE YEMEN
// 349 ARMENIA ARMENIA
// 350 AZERBAIJAN  AZERBAIJAN
// 351 GEORGIA GEORGIA
// 352 KAZAJSTAN   KAZAJSTAN
// 353 KIRGUIZISTAN    KIRGUIZISTAN
// 354 TAYIKISTAN  TAYIKISTAN
// 355 TURKMENISTAN    TURKMENISTAN
// 356 UZBEKISTAN  UZBEKISTAN
// 357 TERR. AU. PALESTINOS    GAZA Y JERICO
// 358 TIMOR ORIENTAL  
// 397 RESTO DE ASIA   RESTO DE ASIA
// 398 INDET.(ASIA)    INDET.(ASIA)
// 401 ALBANIA ALBANIA
// 402 ALEMANIA FEDERAL    ALEMANIA FEDERAL
// 403 ALEMANIA ORIENTAL   ALEMANIA ORIENTAL
// 404 ANDORRA ANDORRA
// 405 AUSTRIA AUSTRIA
// 406 BELGICA BELGICA
// 407 BULGARIA    BULGARIA
// 408 CHECOSLOVAQUIA  CHECOSLOVAQUIA
// 409 DINAMARCA   DINAMARCA
// 410 ESPAÑA  ESPAÑA
// 411 FINLANDIA   FINLANDIA
// 412 FRANCIA FRANCIA
// 413 GRECIA  GRECIA
// 414 HUNGRIA HUNGRIA
// 415 IRLANDA IRLANDA
// 416 ISLANDIA    ISLANDIA
// 417 ITALIA  ITALIA
// 418 LIECHTENSTEIN   LIECHTENSTEIN
// 419 LUXEMBURGO  LUXEMBURGO
// 420 MALTA   MALTA
// 421 MONACO  MONACO
// 422 NORUEGA NORUEGA
// 423 PAISES BAJOS    PAISES BAJOS
// 424 POLONIA POLONIA
// 425 PORTUGAL    PORTUGAL
// 426 REINO UNIDO REINO UNIDO
// 427 RUMANIA RUMANIA
// 428 SAN MARINO  SAN MARINO
// 429 SUECIA  SUECIA
// 430 SUIZA   SUIZA
// 431 VATICANO(SANTA SEDE)    VATICANO(SENTA SEDE)
// 432 YUGOSLAVIA  
// 433 POS.BRIT.(EUROPA)   POS.BRIT.(EUROPA)
// 434 HOLANDA HOLANDA
// 435 CHIPRE  CHIPRE
// 436 TURQUIA TURQUIA
// 438 ALEMANIA,REP.FED.   ALEMANIA,REP.FED.
// 439 BIELORRUSIA BIELORRUSIA
// 440 ESTONIA ESTONIA
// 441 LETONIA LETONIA
// 442 LITUANIA    LITUANIA
// 443 MOLDAVIA    MOLDAVIA
// 444 RUSIA   RUSIA
// 445 UCRANIA UCRANIA
// 446 BOSNIA HERZEGOVINA  BOSNIA HERZEGOVINA
// 447 CROACIA CROACIA
// 448 ESLOVAQUIA  ESLOVAQUIA
// 449 ESLOVENIA   ESLOVENIA
// 450 MACEDONIA   MACEDONIA
// 451 REP. CHECA  REP. CHECA
// 452 FED. SER Y MONT YOGOE   
// 453 MONTENEGRO  MONTENEGRO
// 454 SERBIA  SERBIA
// 497 RESTO EUROPA    RESTO EUROPA
// 498 INDET.(EUROPA)  INDET.(EUROPA)
// 501 AUSTRALIA   AUSTRALIA
// 503 NAURU   NAURU
// 504 NUEVA ZELANDIA  NUEVA ZELANDIA
// 505 VANATU  VANATU
// 506 SAMOA OCCIDENTAL    SAMOA OCCIDENTAL
// 507 TERRITORIO VINCULADOS A AUSTRALIA   OCEANIA
// 508 TERRITORIOS VINCULADOS AL R. UNIDO  OCEANIA
// 509 TERRITORIOS VINCULADOS A FRANCIA    OCEANIA
// 510 TER VINCULADOS A NUEVA. ZELANDA OCEANIA
// 511 TER. VINCULADOS A ESTADOS UNIDOS    OCEANIA
// 512 FIJI, ISLAS FIJI, ISLAS
// 513 PAPUA NUEVA GUINEA  PAPUA NUEVA GUINEA
// 514 KIRIBATI, ISLAS KIRIBATI, ISLAS
// 515 MICRONESIA,EST.FEDER    MICRONESIA,EST.FEDER
// 516 PALAU   PALAU
// 517 TUVALU  TUVALU
// 518 SALOMON,ISLAS   SALOMON,ISLAS
// 519 TONGA   TONGA
// 520 MARSHALL,ISLAS  MARSHALL,ISLAS
// 521 MARIANAS,ISLAS  MARIANAS,ISLAS
// 597 RESTO OCEANIA   RESTO OCEANIA
// 598 INDET.(OCEANIA) INDET.(OCEANIA)
// 601 URSS    URSS
// 652 ANGUILA (TERRITORIO NO AUTONOMO DEL R. UNIDO)   ANGUILA (TERRITORIO NO AUTONOMO DEL R. UNIDO)
// 659 ANTILLAS HOLANDESAS (TERRITORIO DE PAISES BAJOS)    
// 653 ARUBA (TERRITORIO DE PAISES BAJOS)  
// 662 ASCENCION   
// 663 BERMUDAS (TERRITORIO NO AUTONOMO DEL R UNIDO)   
// 664 CAMPIONE DITALIA    
// 665 COLONIA DE GIBRALTAR    
// 666 GROENLANDIA 
// 667 GUAM (TERRITORIO NO AUTONOMO DE LOS ESTADO UNIDOS   
// 668 HONG KONG (TERRITORIO DE CHINA) 
// 669 ISLAS AZORES    
// 670 ISLAS DEL CANAL (GUERNESEY, JERSEY, ALDERNEY,G.STARK, L.SARK, ETC)  
// 671 ISLAS CAIMAN (TERRITORIO NO AUTONOMO DE R UNIDO)    
// 672 ISLA CHRISTMAS  
// 673 ISLA DE COCOS O KEELING 
// 654 ISLA DE COOK (TERRITORIO AUTONOMO ASOCIADO A NUEVA ZELANDA) 
// 676 ISLA DE MAN (TERRITORIO DEL REINO UNIDO)    
// 677 ISLA DE NORFOLK (TERRITORIO DEL R UNIDO)    
// 678 ISALAS TURKAS Y CAICOS (TERRITORIO NO AUTONOMO DEL REINO UNIDO) 
// 679 ISLAS PACIFICO  
// 680 ISLAS DE SAN PEDRO Y MIGUELON   
// 681 ISLA QESHM  
// 682 ISLAS VIRGENES BRITANICAS (TERRITORIO NO AUTONOMO DEL REINO UNIDO)  
// 683 ISLAS VIRGENES DE ESTADOS UNIDOS DE AMERICA 
// 684 LABUAM  
// 685 MADEIRA (TERRITORIO DE PORTUGAL)    
// 686 MONSERRAT (TERRITORIO NO AUTONOMO DEL REINO UNIDO)  
// 687 NIUE    
// 655 PATAU   
// 690 PITCAIRN    
// 656 POLINESI FRANCESA (TERRITORIO DE ULTRAMAR DE FRANCIA)   
// 693 REGIMEN APLICABLE A LAS SA FINANCIERAS (LEY 11073 DE LA ROU)    
// 694 SANTA ELENA 
// 695 SAMAO AMERICANA (TERRITORIO NO AUTONOMO DE LOS ESTADOS UNIDOS)  
// 696 ARCHIPIELAGO DE SVBALBARD   
// 697 TRISTAN DACUNHA 
// 698 TRIESTE (ITALIA)    
// 699 TOKELAU 
// 700 ZONA LIBRE DE OSTRAVA (CIUDAD DE LA ATIGUA CHECOSLOVAQUIA)  
// 997 RESTO CONTINENTE    RESTO CONTINENTE
// 998 INDET.(CONTINENTE)  INDET.(CONTINENTE)
// 999 OTROS PAISES    


        foreach ($paises as $pais) {
            PaisExportacion::create($pais);
        }
    }
}
